#include "bibliotecas.h"

void desenhaGameOver(){
    int i, j;

    desenha_cenario();
    colore_fundo();

    textbackground(BLACK);
    for(i = 0; i < ALTURA_PRETO; i ++){
        for(j = 0; j < LARGURA_PRETO; j++){
            gotoxy(22 + j, 5 + i);
            printf(" ");

            gotoxy(22 + j, 14 + i);
            printf(" ");
        }
    }

    textbackground(DARKGRAY);
    gotoxy(30,19);
    printf(" ");
    gotoxy(38,19);
    printf(" ");


    textbackground(CYAN);

    // G
    gotoxy(22,4);
    printf(" ");
    gotoxy(23,4);
    printf(" ");
    gotoxy(24,4);
    printf(" ");
    gotoxy(25,4);
    printf(" ");
    gotoxy(26,4);
    printf(" ");
    gotoxy(27,4);
    printf(" ");
    gotoxy(28,4);
    printf(" ");
    gotoxy(21,5);
    printf(" ");
    gotoxy(22,5);
    printf(" ");
    gotoxy(28,5);
    printf(" ");
    gotoxy(29,5);
    printf(" ");
    gotoxy(21,6);
    printf(" ");
    gotoxy(24,6);
    printf(" ");
    gotoxy(25,6);
    printf(" ");
    gotoxy(26,6);
    printf(" ");
    gotoxy(29,6);
    printf(" ");
    gotoxy(21,7);
    printf(" ");
    gotoxy(24,7);
    printf(" ");
    gotoxy(25,7);
    printf(" ");
    gotoxy(26,7);
    printf(" ");
    gotoxy(27,7);
    printf(" ");
    gotoxy(28,7);
    printf(" ");
    gotoxy(29,7);
    printf(" ");
    gotoxy(21,8);
    printf(" ");
    gotoxy(24,8);
    printf(" ");
    gotoxy(25,8);
    printf(" ");
    gotoxy(29,8);
    printf(" ");
    gotoxy(21,9);
    printf(" ");
    gotoxy(24,9);
    printf(" ");
    gotoxy(25,9);
    printf(" ");
    gotoxy(26,9);
    printf(" ");
    gotoxy(29,9);
    printf(" ");
    gotoxy(21,10);
    printf(" ");
    gotoxy(22,10);
    printf(" ");
    gotoxy(27,10);
    printf(" ");
    gotoxy(29,10);
    printf(" ");
    gotoxy(22,11);
    printf(" ");
    gotoxy(23,11);
    printf(" ");
    gotoxy(24,11);
    printf(" ");
    gotoxy(25,11);
    printf(" ");
    gotoxy(26,11);
    printf(" ");
    gotoxy(27,11);
    printf(" ");
    gotoxy(28,11);
    printf(" ");
    gotoxy(29,11);
    printf(" ");

    // A
    gotoxy(31,4);
    printf(" ");
    gotoxy(32,4);
    printf(" ");
    gotoxy(33,4);
    printf(" ");
    gotoxy(34,4);
    printf(" ");
    gotoxy(35,4);
    printf(" ");
    gotoxy(36,4);
    printf(" ");
    gotoxy(37,4);
    printf(" ");
    gotoxy(30,5);
    printf(" ");
    gotoxy(31,5);
    printf(" ");
    gotoxy(37,5);
    printf(" ");
    gotoxy(38,5);
    printf(" ");
    gotoxy(30,6);
    printf(" ");
    gotoxy(33,6);
    printf(" ");
    gotoxy(34,6);
    printf(" ");
    gotoxy(35,6);
    printf(" ");
    gotoxy(38,6);
    printf(" ");
    gotoxy(30,7);
    printf(" ");
    gotoxy(33,7);
    printf(" ");
    gotoxy(34,7);
    printf(" ");
    gotoxy(35,7);
    printf(" ");
    gotoxy(38,7);
    printf(" ");
    gotoxy(30,8);
    printf(" ");
    gotoxy(38,8);
    printf(" ");
    gotoxy(30,9);
    printf(" ");
    gotoxy(33,9);
    printf(" ");
    gotoxy(34,9);
    printf(" ");
    gotoxy(35,9);
    printf(" ");
    gotoxy(38,9);
    printf(" ");
    gotoxy(30,10);
    printf(" ");
    gotoxy(33,10);
    printf(" ");
    gotoxy(34,10);
    printf(" ");
    gotoxy(35,10);
    printf(" ");
    gotoxy(38,10);
    printf(" ");
    gotoxy(30,11);
    printf(" ");
    gotoxy(31,11);
    printf(" ");
    gotoxy(32,11);
    printf(" ");
    gotoxy(33,11);
    printf(" ");
    gotoxy(34,11);
    printf(" ");
    gotoxy(35,11);
    printf(" ");
    gotoxy(36,11);
    printf(" ");
    gotoxy(37,11);
    printf(" ");
    gotoxy(38,11);
    printf(" ");

    // M
    gotoxy(39,4);
    printf(" ");
    gotoxy(40,4);
    printf(" ");
    gotoxy(41,4);
    printf(" ");
    gotoxy(42,4);
    printf(" ");
    gotoxy(43,4);
    printf(" ");
    gotoxy(45,4);
    printf(" ");
    gotoxy(46,4);
    printf(" ");
    gotoxy(47,4);
    printf(" ");
    gotoxy(48,4);
    printf(" ");
    gotoxy(49,4);
    printf(" ");
    gotoxy(39,5);
    printf(" ");
    gotoxy(43,5);
    printf(" ");
    gotoxy(44,5);
    printf(" ");
    gotoxy(45,5);
    printf(" ");
    gotoxy(49,5);
    printf(" ");
    gotoxy(39,6);
    printf(" ");
    gotoxy(44,6);
    printf(" ");
    gotoxy(49,6);
    printf(" ");
    gotoxy(39,7);
    printf(" ");
    gotoxy(49,7);
    printf(" ");
    gotoxy(39,8);
    printf(" ");
    gotoxy(43,8);
    printf(" ");
    gotoxy(45,8);
    printf(" ");
    gotoxy(49,8);
    printf(" ");
    gotoxy(39,9);
    printf(" ");
    gotoxy(43,9);
    printf(" ");
    gotoxy(44,9);
    printf(" ");
    gotoxy(45,9);
    printf(" ");
    gotoxy(49,9);
    printf(" ");
    gotoxy(39,10);
    printf(" ");
    gotoxy(43,10);
    printf(" ");
    gotoxy(44,10);
    printf(" ");
    gotoxy(45,10);
    printf(" ");
    gotoxy(49,10);
    printf(" ");
    gotoxy(39,11);
    printf(" ");
    gotoxy(40,11);
    printf(" ");
    gotoxy(41,11);
    printf(" ");
    gotoxy(42,11);
    printf(" ");
    gotoxy(43,11);
    printf(" ");
    gotoxy(44,11);
    printf(" ");
    gotoxy(45,11);
    printf(" ");
    gotoxy(46,11);
    printf(" ");
    gotoxy(47,11);
    printf(" ");
    gotoxy(48,11);
    printf(" ");
    gotoxy(49,11);
    printf(" ");

    // E
    gotoxy(50,4);
    printf(" ");
    gotoxy(51,4);
    printf(" ");
    gotoxy(52,4);
    printf(" ");
    gotoxy(53,4);
    printf(" ");
    gotoxy(54,4);
    printf(" ");
    gotoxy(55,4);
    printf(" ");
    gotoxy(56,4);
    printf(" ");
    gotoxy(57,4);
    printf(" ");
    gotoxy(50,5);
    printf(" ");
    gotoxy(57,5);
    printf(" ");
    gotoxy(50,6);
    printf(" ");
    gotoxy(53,6);
    printf(" ");
    gotoxy(54,6);
    printf(" ");
    gotoxy(55,6);
    printf(" ");
    gotoxy(56,6);
    printf(" ");
    gotoxy(57,6);
    printf(" ");
    gotoxy(50,7);
    printf(" ");
    gotoxy(56,7);
    printf(" ");
    gotoxy(57,7);
    printf(" ");
    gotoxy(50,8);
    printf(" ");
    gotoxy(53,8);
    printf(" ");
    gotoxy(54,8);
    printf(" ");
    gotoxy(55,8);
    printf(" ");
    gotoxy(56,8);
    printf(" ");
    gotoxy(57,8);
    printf(" ");
    gotoxy(50,9);
    printf(" ");
    gotoxy(53,9);
    printf(" ");
    gotoxy(54,9);
    printf(" ");
    gotoxy(55,9);
    printf(" ");
    gotoxy(56,9);
    printf(" ");
    gotoxy(57,9);
    printf(" ");
    gotoxy(50,10);
    printf(" ");
    gotoxy(57,10);
    printf(" ");
    gotoxy(50,11);
    printf(" ");
    gotoxy(51,11);
    printf(" ");
    gotoxy(52,11);
    printf(" ");
    gotoxy(53,11);
    printf(" ");
    gotoxy(54,11);
    printf(" ");
    gotoxy(55,11);
    printf(" ");
    gotoxy(56,11);
    printf(" ");
    gotoxy(57,11);
    printf(" ");

    // O
    gotoxy(22,13);
    printf(" ");
    gotoxy(23,13);
    printf(" ");
    gotoxy(24,13);
    printf(" ");
    gotoxy(25,13);
    printf(" ");
    gotoxy(26,13);
    printf(" ");
    gotoxy(27,13);
    printf(" ");
    gotoxy(28,13);
    printf(" ");
    gotoxy(21,14);
    printf(" ");
    gotoxy(22,14);
    printf(" ");
    gotoxy(28,14);
    printf(" ");
    gotoxy(29,14);
    printf(" ");
    gotoxy(21,15);
    printf(" ");
    gotoxy(24,15);
    printf(" ");
    gotoxy(25,15);
    printf(" ");
    gotoxy(26,15);
    printf(" ");
    gotoxy(29,15);
    printf(" ");
    gotoxy(21,16);
    printf(" ");
    gotoxy(24,16);
    printf(" ");
    gotoxy(25,16);
    printf(" ");
    gotoxy(26,16);
    printf(" ");
    gotoxy(29,16);
    printf(" ");
    gotoxy(21,17);
    printf(" ");
    gotoxy(24,17);
    printf(" ");
    gotoxy(25,17);
    printf(" ");
    gotoxy(26,17);
    printf(" ");
    gotoxy(29,17);
    printf(" ");
    gotoxy(21,18);
    printf(" ");
    gotoxy(24,18);
    printf(" ");
    gotoxy(25,18);
    printf(" ");
    gotoxy(26,18);
    printf(" ");
    gotoxy(29,18);
    printf(" ");
    gotoxy(21,19);
    printf(" ");
    gotoxy(22,19);
    printf(" ");
    gotoxy(28,19);
    printf(" ");
    gotoxy(29,19);
    printf(" ");
    gotoxy(22,20);
    printf(" ");
    gotoxy(23,20);
    printf(" ");
    gotoxy(24,20);
    printf(" ");
    gotoxy(25,20);
    printf(" ");
    gotoxy(26,20);
    printf(" ");
    gotoxy(27,20);
    printf(" ");
    gotoxy(28,20);
    printf(" ");

    // V
    gotoxy(30,13);
    printf(" ");
    gotoxy(31,13);
    printf(" ");
    gotoxy(32,13);
    printf(" ");
    gotoxy(33,13);
    printf(" ");
    gotoxy(35,13);
    printf(" ");
    gotoxy(36,13);
    printf(" ");
    gotoxy(37,13);
    printf(" ");
    gotoxy(38,13);
    printf(" ");
    gotoxy(30,14);
    printf(" ");
    gotoxy(33,14);
    printf(" ");
    gotoxy(34,14);
    printf(" ");
    gotoxy(35,14);
    printf(" ");
    gotoxy(38,14);
    printf(" ");
    gotoxy(30,15);
    printf(" ");
    gotoxy(33,15);
    printf(" ");
    gotoxy(34,15);
    printf(" ");
    gotoxy(35,15);
    printf(" ");
    gotoxy(38,15);
    printf(" ");
    gotoxy(30,16);
    printf(" ");
    gotoxy(33,16);
    printf(" ");
    gotoxy(34,16);
    printf(" ");
    gotoxy(35,16);
    printf(" ");
    gotoxy(38,16);
    printf(" ");
    gotoxy(30,17);
    printf(" ");
    gotoxy(31,17);
    printf(" ");
    gotoxy(34,17);
    printf(" ");
    gotoxy(37,17);
    printf(" ");
    gotoxy(38,17);
    printf(" ");
    gotoxy(30,18);
    printf(" ");
    gotoxy(31,18);
    printf(" ");
    gotoxy(32,18);
    printf(" ");
    gotoxy(36,18);
    printf(" ");
    gotoxy(37,18);
    printf(" ");
    gotoxy(38,18);
    printf(" ");
    gotoxy(31,19);
    printf(" ");
    gotoxy(32,19);
    printf(" ");
    gotoxy(33,19);
    printf(" ");
    gotoxy(35,19);
    printf(" ");
    gotoxy(36,19);
    printf(" ");
    gotoxy(37,19);
    printf(" ");
    gotoxy(32,20);
    printf(" ");
    gotoxy(33,20);
    printf(" ");
    gotoxy(34,20);
    printf(" ");
    gotoxy(35,20);
    printf(" ");
    gotoxy(36,20);
    printf(" ");

    // E
    gotoxy(39,13);
    printf(" ");
    gotoxy(40,13);
    printf(" ");
    gotoxy(41,13);
    printf(" ");
    gotoxy(42,13);
    printf(" ");
    gotoxy(43,13);
    printf(" ");
    gotoxy(44,13);
    printf(" ");
    gotoxy(45,13);
    printf(" ");
    gotoxy(46,13);
    printf(" ");
    gotoxy(39,14);
    printf(" ");
    gotoxy(46,14);
    printf(" ");
    gotoxy(39,15);
    printf(" ");
    gotoxy(42,15);
    printf(" ");
    gotoxy(43,15);
    printf(" ");
    gotoxy(44,15);
    printf(" ");
    gotoxy(45,15);
    printf(" ");
    gotoxy(46,15);
    printf(" ");
    gotoxy(39,16);
    printf(" ");
    gotoxy(45,16);
    printf(" ");
    gotoxy(46,16);
    printf(" ");
    gotoxy(39,17);
    printf(" ");
    gotoxy(42,17);
    printf(" ");
    gotoxy(43,17);
    printf(" ");
    gotoxy(44,17);
    printf(" ");
    gotoxy(45,17);
    printf(" ");
    gotoxy(46,17);
    printf(" ");
    gotoxy(39,18);
    printf(" ");
    gotoxy(42,18);
    printf(" ");
    gotoxy(43,18);
    printf(" ");
    gotoxy(44,18);
    printf(" ");
    gotoxy(45,18);
    printf(" ");
    gotoxy(46,18);
    printf(" ");
    gotoxy(39,19);
    printf(" ");
    gotoxy(46,19);
    printf(" ");
    gotoxy(39,20);
    printf(" ");
    gotoxy(40,20);
    printf(" ");
    gotoxy(41,20);
    printf(" ");
    gotoxy(42,20);
    printf(" ");
    gotoxy(43,20);
    printf(" ");
    gotoxy(44,20);
    printf(" ");
    gotoxy(45,20);
    printf(" ");
    gotoxy(46,20);
    printf(" ");

    // R
    gotoxy(47,13);
    printf(" ");
    gotoxy(48,13);
    printf(" ");
    gotoxy(49,13);
    printf(" ");
    gotoxy(50,13);
    printf(" ");
    gotoxy(51,13);
    printf(" ");
    gotoxy(52,13);
    printf(" ");
    gotoxy(53,13);
    printf(" ");
    gotoxy(54,13);
    printf(" ");
    gotoxy(55,13);
    printf(" ");

    gotoxy(47,14);
    printf(" ");
    gotoxy(55,14);
    printf(" ");
    gotoxy(56,14);
    printf(" ");

    gotoxy(47,15);
    printf(" ");
    gotoxy(50,15);
    printf(" ");
    gotoxy(51,15);
    printf(" ");
    gotoxy(52,15);
    printf(" ");
    gotoxy(56,15);
    printf(" ");

    gotoxy(47,16);
    printf(" ");
    gotoxy(50,16);
    printf(" ");
    gotoxy(51,16);
    printf(" ");
    gotoxy(52,16);
    printf(" ");
    gotoxy(56,16);
    printf(" ");

    gotoxy(47,17);
    printf(" ");
    gotoxy(55,17);
    printf(" ");
    gotoxy(56,17);
    printf(" ");

    gotoxy(47,18);
    printf(" ");
    gotoxy(50,18);
    printf(" ");
    gotoxy(51,18);
    printf(" ");
    gotoxy(52,18);
    printf(" ");
    gotoxy(56,18);
    printf(" ");

    gotoxy(47,19);
    printf(" ");
    gotoxy(50,19);
    printf(" ");
    gotoxy(51,19);
    printf(" ");
    gotoxy(52,19);
    printf(" ");
    gotoxy(56,19);
    printf(" ");

    gotoxy(47,20);
    printf(" ");
    gotoxy(48,20);
    printf(" ");
    gotoxy(49,20);
    printf(" ");
    gotoxy(50,20);
    printf(" ");
    gotoxy(51,20);
    printf(" ");
    gotoxy(52,20);
    printf(" ");
    gotoxy(53,20);
    printf(" ");
    gotoxy(54,20);
    printf(" ");
    gotoxy(55,20);
    printf(" ");
    gotoxy(56,20);
    printf(" ");

    // Volta as cores default
    textbackground(BLACK);
    textcolor(WHITE);
}

void desenhaInicio(){
    int i;

    desenha_cenario();
    colore_fundo();

    textbackground(DARKGRAY);
    textcolor(BLACK);

    // Cowboy
    gotoxy(15, 6);
    printf("___");
    gotoxy(12, 7);
    printf("__|___|__");
    gotoxy(13, 8);
    printf("('o_o')");
    gotoxy(13, 9);
    printf("_\\~-~/_    ______.");
    gotoxy(12, 10);
    printf("//\\__/\\ \\ ~(_]---'");
    gotoxy(11, 11);
    printf("/ )O  O( .\\/_)");
    gotoxy(11, 12);
    printf("\\ \\    / \\_/");
    gotoxy(11, 13);
    printf(")/_|  |_\\");
    gotoxy(10, 14);
    printf("// /(\\/)\\ \\");
    gotoxy(10, 15);
    printf("/_/      \\_\\");
    gotoxy(9, 16);
    printf("(_||      ||_)");
    gotoxy(11, 17);
    printf("\\| |__| |/");
    gotoxy(12, 18);
    printf("| |  | |");
    gotoxy(12, 19);
    printf("| |  | |");
    gotoxy(7, 20);
    printf("_____|_|__|_|_____");
    gotoxy(9, 21);
    printf("-  /_\\  /_\\ -");
    gotoxy(7, 22);
    printf("-   -      -    -");


    gotoxy(35, 15);
    printf("Capture todos os bandidos e mantenha sua");
    gotoxy(48,16);
    printf("cidade segura");

    textbackground(CYAN);
    textcolor(BLUE);

    for(i = 0; i < 3; i++){
        gotoxy(38, 8 + i);
        printf("|                               |");
    }

    textcolor(BLACK);
    gotoxy(41,9);
    printf("Bem-vindo ao");

    textcolor(WHITE);
    gotoxy(54,9);
    printf("*Xerife Run*");

    // Volta as cores default
    textbackground(BLACK);
    textcolor(WHITE);
}

void desenhaVitoria(){
    int i, j;

    for(i = 0; i < LINHASPAREDE; i++){
        for(j = 0; j < COLUNASPAREDE; j++){
            if(j == 0 || j == COLUNASPAREDE - 1 || i == 0 || i == LINHASPAREDE - 1){
                textbackground(BLUE);
                printf(" ");
            } else {
                textbackground(BLACK);
                printf(" ");
            }
        }
        printf("\n");
    }

    textbackground(CYAN);

    // Y
    gotoxy(30,4);
    printf(" ");
    gotoxy(31,4);
    printf(" ");
    gotoxy(34,4);
    printf(" ");
    gotoxy(35,4);
    printf(" ");
    gotoxy(30,5);
    printf(" ");
    gotoxy(31,5);
    printf(" ");
    gotoxy(34,5);
    printf(" ");
    gotoxy(35,5);
    printf(" ");
    gotoxy(30,6);
    printf(" ");
    gotoxy(31,6);
    printf(" ");
    gotoxy(34,6);
    printf(" ");
    gotoxy(35,6);
    printf(" ");
    gotoxy(31,7);
    printf(" ");
    gotoxy(32,7);
    printf(" ");
    gotoxy(33, 7);
    printf(" ");
    gotoxy(34,7);
    printf(" ");
    gotoxy(32,8);
    printf(" ");
    gotoxy(33, 8);
    printf(" ");
    gotoxy(32,9);
    printf(" ");
    gotoxy(33, 9);
    printf(" ");
    gotoxy(32,10);
    printf(" ");
    gotoxy(33, 10);
    printf(" ");
    gotoxy(32,11);
    printf(" ");
    gotoxy(33, 11);
    printf(" ");

    // O
    gotoxy(39, 4);
    printf(" ");
    gotoxy(40, 4);
    printf(" ");
    gotoxy(41, 4);
    printf(" ");
    gotoxy(42, 4);
    printf(" ");
    gotoxy(38, 5);
    printf(" ");
    gotoxy(39, 5);
    printf(" ");
    gotoxy(42, 5);
    printf(" ");
    gotoxy(43, 5);
    printf(" ");
    gotoxy(38, 6);
    printf(" ");
    gotoxy(39, 6);
    printf(" ");
    gotoxy(42, 6);
    printf(" ");
    gotoxy(43, 6);
    printf(" ");
    gotoxy(38, 7);
    printf(" ");
    gotoxy(39, 7);
    printf(" ");
    gotoxy(42, 7);
    printf(" ");
    gotoxy(43, 7);
    printf(" ");
    gotoxy(38, 8);
    printf(" ");
    gotoxy(39, 8);
    printf(" ");
    gotoxy(42, 8);
    printf(" ");
    gotoxy(43, 8);
    printf(" ");
    gotoxy(38, 9);
    printf(" ");
    gotoxy(39, 9);
    printf(" ");
    gotoxy(42, 9);
    printf(" ");
    gotoxy(43, 9);
    printf(" ");
    gotoxy(38, 10);
    printf(" ");
    gotoxy(39, 10);
    printf(" ");
    gotoxy(42, 10);
    printf(" ");
    gotoxy(43, 10);
    printf(" ");
    gotoxy(39, 11);
    printf(" ");
    gotoxy(40, 11);
    printf(" ");
    gotoxy(41, 11);
    printf(" ");
    gotoxy(42, 11);
    printf(" ");

    // U
    gotoxy(46, 4);
    printf(" ");
    gotoxy(47, 4);
    printf(" ");
    gotoxy(50, 4);
    printf(" ");
    gotoxy(51, 4);
    printf(" ");
    gotoxy(46, 5);
    printf(" ");
    gotoxy(47, 5);
    printf(" ");
    gotoxy(50, 5);
    printf(" ");
    gotoxy(51,5);
    printf(" ");
    gotoxy(46, 6);
    printf(" ");
    gotoxy(47, 6);
    printf(" ");
    gotoxy(50, 6);
    printf(" ");
    gotoxy(51, 6);
    printf(" ");
    gotoxy(46, 7);
    printf(" ");
    gotoxy(47, 7);
    printf(" ");
    gotoxy(50, 7);
    printf(" ");
    gotoxy(51, 7);
    printf(" ");
    gotoxy(46, 8);
    printf(" ");
    gotoxy(47, 8);
    printf(" ");
    gotoxy(50, 8);
    printf(" ");
    gotoxy(51, 8);
    printf(" ");
    gotoxy(46, 9);
    printf(" ");
    gotoxy(47, 9);
    printf(" ");
    gotoxy(50, 9);
    printf(" ");
    gotoxy(51, 9);
    printf(" ");
    gotoxy(46, 10);
    printf(" ");
    gotoxy(47, 10);
    printf(" ");
    gotoxy(50, 10);
    printf(" ");
    gotoxy(51, 10);
    printf(" ");
    gotoxy(47, 11);
    printf(" ");
    gotoxy(48, 11);
    printf(" ");
    gotoxy(49, 11);
    printf(" ");
    gotoxy(50, 11);
    printf(" ");

    // W
    gotoxy(27, 13);
    printf(" ");
    gotoxy(28, 13);
    printf(" ");
    gotoxy(32, 13);
    printf(" ");
    gotoxy(33, 13);
    printf(" ");

    gotoxy(27, 14);
    printf(" ");
    gotoxy(28, 14);
    printf(" ");
    gotoxy(32, 14);
    printf(" ");
    gotoxy(33, 14);
    printf(" ");

    gotoxy(27, 15);
    printf(" ");
    gotoxy(28, 15);
    printf(" ");
    gotoxy(32, 15);
    printf(" ");
    gotoxy(33, 15);
    printf(" ");

    gotoxy(27, 16);
    printf(" ");
    gotoxy(28, 16);
    printf(" ");
    gotoxy(30, 16);
    printf(" ");
    gotoxy(32, 16);
    printf(" ");
    gotoxy(33, 16);
    printf(" ");

    gotoxy(27, 17);
    printf(" ");
    gotoxy(28, 17);
    printf(" ");
    gotoxy(30, 17);
    printf(" ");
    gotoxy(32, 17);
    printf(" ");
    gotoxy(33, 17);
    printf(" ");

    gotoxy(28, 18);
    printf(" ");
    gotoxy(29, 18);
    printf(" ");
    gotoxy(31, 18);
    printf(" ");
    gotoxy(32, 18);
    printf(" ");

    gotoxy(28, 19);
    printf(" ");
    gotoxy(29, 19);
    printf(" ");
    gotoxy(31, 19);
    printf(" ");
    gotoxy(32, 19);
    printf(" ");

    gotoxy(28, 20);
    printf(" ");
    gotoxy(29, 20);
    printf(" ");
    gotoxy(31, 20);
    printf(" ");
    gotoxy(32, 20);
    printf(" ");

    // I
    gotoxy(36, 13);
    printf(" ");
    gotoxy(37, 13);
    printf(" ");
    gotoxy(38, 13);
    printf(" ");
    gotoxy(39, 13);
    printf(" ");
    gotoxy(37, 14);
    printf(" ");
    gotoxy(38, 14);
    printf(" ");
    gotoxy(37, 15);
    printf(" ");
    gotoxy(38, 15);
    printf(" ");
    gotoxy(37, 16);
    printf(" ");
    gotoxy(38, 16);
    printf(" ");
    gotoxy(37, 17);
    printf(" ");
    gotoxy(38, 17);
    printf(" ");
    gotoxy(37, 18);
    printf(" ");
    gotoxy(38, 18);
    printf(" ");
    gotoxy(37, 19);
    printf(" ");
    gotoxy(38, 19);
    printf(" ");
    gotoxy(36, 20);
    printf(" ");
    gotoxy(37, 20);
    printf(" ");
    gotoxy(38, 20);
    printf(" ");
    gotoxy(39, 20);
    printf(" ");

    // N
    gotoxy(42, 13);
    printf(" ");
    gotoxy(43, 13);
    printf(" ");
    gotoxy(47, 13);
    printf(" ");
    gotoxy(48, 13);
    printf(" ");

    gotoxy(42, 14);
    printf(" ");
    gotoxy(43, 14);
    printf(" ");
    gotoxy(47, 14);
    printf(" ");
    gotoxy(48, 14);
    printf(" ");

    gotoxy(42, 15);
    printf(" ");
    gotoxy(43, 15);
    printf(" ");
    gotoxy(44, 15);
    printf(" ");
    gotoxy(47, 15);
    printf(" ");
    gotoxy(48, 15);
    printf(" ");

    gotoxy(42, 16);
    printf(" ");
    gotoxy(43, 16);
    printf(" ");
    gotoxy(44, 16);
    printf(" ");
    gotoxy(45, 16);
    printf(" ");
    gotoxy(47, 16);
    printf(" ");
    gotoxy(48, 16);
    printf(" ");

    gotoxy(42, 17);
    printf(" ");
    gotoxy(43, 17);
    printf(" ");
    gotoxy(45, 17);
    printf(" ");
    gotoxy(46, 17);
    printf(" ");
    gotoxy(47, 17);
    printf(" ");
    gotoxy(48, 17);
    printf(" ");

    gotoxy(42, 18);
    printf(" ");
    gotoxy(43, 18);
    printf(" ");
    gotoxy(46, 18);
    printf(" ");
    gotoxy(47, 18);
    printf(" ");
    gotoxy(48, 18);
    printf(" ");

    gotoxy(42, 19);
    printf(" ");
    gotoxy(43, 19);
    printf(" ");
    gotoxy(47, 19);
    printf(" ");
    gotoxy(48, 19);
    printf(" ");

    gotoxy(42, 20);
    printf(" ");
    gotoxy(43, 20);
    printf(" ");
    gotoxy(47, 20);
    printf(" ");
    gotoxy(48, 20);
    printf(" ");

    // !
    gotoxy(52, 13);
    printf(" ");
    gotoxy(53, 13);
    printf(" ");
    gotoxy(51, 14);
    printf(" ");
    gotoxy(52, 14);
    printf(" ");
    gotoxy(53, 14);
    printf(" ");
    gotoxy(54, 14);
    printf(" ");
    gotoxy(51, 15);
    printf(" ");
    gotoxy(52, 15);
    printf(" ");
    gotoxy(53, 15);
    printf(" ");
    gotoxy(54, 15);
    printf(" ");
    gotoxy(52, 16);
    printf(" ");
    gotoxy(53, 16);
    printf(" ");
    gotoxy(52, 17);
    printf(" ");
    gotoxy(53, 17);
    printf(" ");
    gotoxy(52, 19);
    printf(" ");
    gotoxy(53, 19);
    printf(" ");
    gotoxy(52, 20);
    printf(" ");
    gotoxy(53, 20);
    printf(" ");

    // Volta as cores default
    textbackground(BLACK);
    textcolor(WHITE);

}
